// Package gosp compiles JSP-style .gosp pages to ordinary Go HTTP handlers.
// Pages contain trusted Go source code and must not be accepted from untrusted users.
package gosp

import (
	"fmt"
	"go/format"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

type fragmentKind uint8

const (
	literal fragmentKind = iota
	statement
	escapedExpression
	rawExpression
)

type fragment struct {
	kind  fragmentKind
	value string
}

type page struct {
	file       string
	function   string
	route      string
	fragments  []fragment
	imports    []string
	hasEscaped bool
	hasRaw     bool
}

// Generate reads all .gosp files under dir and returns a formatted Go source file
// in the requested package. A page named index.gosp is mapped to /, while
// admin/index.gosp is mapped to /admin/ and about.gosp to /about.
// Generated functions have the signature func RenderX(http.ResponseWriter, *http.Request).
func Generate(dir, packageName string) ([]byte, error) {
	if !token.IsIdentifier(packageName) || packageName == "_" {
		return nil, fmt.Errorf("invalid Go package name %q", packageName)
	}
	var files []string
	err := filepath.WalkDir(dir, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() && filepath.Ext(entry.Name()) == ".gosp" {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("no .gosp files found in %s", dir)
	}
	sort.Strings(files)
	var pages []page
	seenFunctions, seenRoutes := map[string]string{}, map[string]string{}
	imports := map[string]bool{"io": true, "net/http": true, "strings": true}
	for _, file := range files {
		rel, err := filepath.Rel(dir, file)
		if err != nil {
			return nil, err
		}
		name := filepath.ToSlash(strings.TrimSuffix(rel, filepath.Ext(rel)))
		function, route, err := namesFor(name)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", rel, err)
		}
		if other := seenFunctions[function]; other != "" {
			return nil, fmt.Errorf("%s and %s both generate %s", other, rel, function)
		}
		if other := seenRoutes[route]; other != "" {
			return nil, fmt.Errorf("%s and %s both map to %s", other, rel, route)
		}
		seenFunctions[function], seenRoutes[route] = rel, rel
		input, err := os.ReadFile(file)
		if err != nil {
			return nil, err
		}
		p, err := parse(rel, string(input))
		if err != nil {
			return nil, err
		}
		p.file, p.function, p.route = rel, function, route
		pages = append(pages, p)
		for _, imp := range p.imports {
			imports[imp] = true
		}
		if p.hasEscaped {
			imports["fmt"], imports["html"] = true, true
		}
		if p.hasRaw {
			imports["fmt"] = true
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gosp; DO NOT EDIT.\npackage %s\n\nimport (\n", packageName)
	var importNames []string
	for path := range imports {
		importNames = append(importNames, path)
	}
	sort.Strings(importNames)
	for _, path := range importNames {
		fmt.Fprintf(&b, "\t%q\n", path)
	}
	b.WriteString(")\n\n")
	for _, p := range pages {
		fmt.Fprintf(&b, "// %s renders %s.\nfunc %s(w http.ResponseWriter, r *http.Request) {\n", p.function, p.file, p.function)
		b.WriteString("var _gospOutput strings.Builder\n")
		for _, f := range p.fragments {
			switch f.kind {
			case literal:
				fmt.Fprintf(&b, "_gospOutput.WriteString(%s)\n", strconv.Quote(f.value))
			case statement:
				b.WriteString(f.value)
				b.WriteString("\n")
			case escapedExpression:
				fmt.Fprintf(&b, "_gospOutput.WriteString(html.EscapeString(fmt.Sprint(%s)))\n", f.value)
			case rawExpression:
				fmt.Fprintf(&b, "_gospOutput.WriteString(fmt.Sprint(%s))\n", f.value)
			}
		}
		b.WriteString("if w.Header().Get(\"Content-Type\") == \"\" { w.Header().Set(\"Content-Type\", \"text/html; charset=utf-8\") }\n")
		b.WriteString("_, _ = io.WriteString(w, _gospOutput.String())\n}\n\n")
	}
	b.WriteString("// RegisterPages registers all generated page routes on mux.\n")
	b.WriteString("func RegisterPages(mux *http.ServeMux) {\n")
	for _, p := range pages {
		pattern := p.route
		if strings.HasSuffix(pattern, "/") {
			pattern += "{$}" // match only the directory index, not its descendants
		}
		fmt.Fprintf(&b, "mux.HandleFunc(%q, %s)\n", pattern, p.function)
	}
	b.WriteString("}\n")
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("invalid generated Go code: %w (check your template Go statements)", err)
	}
	return out, nil
}

func namesFor(name string) (function string, route string, err error) {
	segments := strings.Split(name, "/")
	for _, s := range segments {
		if s == "" {
			return "", "", fmt.Errorf("empty page path segment")
		}
		for _, ch := range s {
			if !((ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') || ch == '_' || ch == '-') {
				return "", "", fmt.Errorf("unsupported page path segment %q (use ASCII letters, numbers, - or _)", s)
			}
		}
	}
	for _, segment := range segments {
		for _, word := range strings.FieldsFunc(segment, func(r rune) bool { return r == '-' || r == '_' }) {
			if len(word) == 0 {
				continue
			}
			runes := []rune(word)
			runes[0] = unicode.ToUpper(runes[0])
			function += string(runes)
		}
	}
	if function == "" {
		return "", "", fmt.Errorf("page name must contain letters or numbers")
	}
	function = "Render" + function
	if segments[len(segments)-1] == "index" {
		if len(segments) == 1 {
			return function, "/", nil
		}
		return function, "/" + strings.Join(segments[:len(segments)-1], "/") + "/", nil
	}
	return function, "/" + name, nil
}
