// Code generated by gosp; DO NOT EDIT.
package main

import (
	"fmt"
	"html"
	"io"
	"net/http"
	"strings"
)

// RenderAbout renders about.gosp.
func RenderAbout(w http.ResponseWriter, r *http.Request) {
	var _gospOutput strings.Builder
	_gospOutput.WriteString("\n<!doctype html>\n<html lang=\"en\">\n<head><meta charset=\"utf-8\"><title>About GOSP</title></head>\n<body>\n  <h1>About GOSP</h1>\n  <p>This text is rendered using a raw expression: ")
	_gospOutput.WriteString(fmt.Sprint("<strong>Go-powered</strong>"))
	_gospOutput.WriteString("</p>\n  <a href=\"/\">Go back</a>\n</body>\n</html>\n")
	if w.Header().Get("Content-Type") == "" {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
	}
	_, _ = io.WriteString(w, _gospOutput.String())
}

// RenderIndex renders index.gosp.
func RenderIndex(w http.ResponseWriter, r *http.Request) {
	var _gospOutput strings.Builder
	_gospOutput.WriteString("\n")
	name := strings.TrimSpace(r.URL.Query().Get("name"))
	if name == "" {
		name = "World"
	}
	_gospOutput.WriteString("\n<!doctype html>\n<html lang=\"en\">\n<head><meta charset=\"utf-8\"><title>GOSP example</title></head>\n<body>\n  <h1>Hello, ")
	_gospOutput.WriteString(html.EscapeString(fmt.Sprint(name)))
	_gospOutput.WriteString("!</h1>\n  <p>These items are generated with a Go loop:</p>\n  <ul>\n  ")
	for n := 1; n <= 3; n++ {
		_gospOutput.WriteString("\n    <li>Item ")
		_gospOutput.WriteString(html.EscapeString(fmt.Sprint(n)))
		_gospOutput.WriteString("</li>\n  ")
	}
	_gospOutput.WriteString("\n  </ul>\n  <form method=\"GET\">\n    <label>Your name: <input name=\"name\" value=\"")
	_gospOutput.WriteString(html.EscapeString(fmt.Sprint(name)))
	_gospOutput.WriteString("\"></label>\n    <button type=\"submit\">Say hello</button>\n  </form>\n  <a href=\"/about\">About this example</a>\n</body>\n</html>\n")
	if w.Header().Get("Content-Type") == "" {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
	}
	_, _ = io.WriteString(w, _gospOutput.String())
}

// RegisterPages registers all generated page routes on mux.
func RegisterPages(mux *http.ServeMux) {
	mux.HandleFunc("/about", RenderAbout)
	mux.HandleFunc("/{$}", RenderIndex)
}
